[package]
name = "mnist-webasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
linear-algebra = {path = "../linear-algebra"}
neural-network = {path = "../neural-network"}
wasm-bindgen = "0.2.88"
